#include "defines.h"
#include "structs.h"

#include "colorgrp.h"
#include "players.h"
#include "dice.h"
#include "bank.h"
#include "board.h"
#include "cards.h"
#include "gamestat.h"
#include "options.h"
#include "property.h"
#include "mcgaprim/gbuffer.h"

#ifndef DLL_BUILD
HWND Main_Window_Handle;
HDC WinG_DC;
int DIB_Top_Down;
int DIB_Bottom_Up;
void *WinG_Buffer_Ptr;
MemorySaveGameClass Memory_Save_Games[3];
int Is_Palette_Device;
int Is_Supported_Depth;
int System_Screen_Width;
int System_Screen_Height;
int System_Border_Width;
int System_Border_Height;
int System_Caption_Height;
int System_Menu_Bar_Height;

char Executable_Path[200];
char CD_Root_Path[200];
char Text_String[255];
char Text_String_2[255];
char Text_String_3[255];

char *Site_Receive_Message_Strings[TOTAL_PLAYERS];

HINSTANCE Global_Instance_Handle;

unsigned int Monopoly_Start_Time;

HPALETTE Main_Palette_Handle;
MSG Global_Message_Queue;

char *String_TRR_Data;
char *Scores_String_TRR_Data;
char *AI_String_TRR_Data;
char *Facts_String_TRR_Data;
char *Deeds_String_TRR_Data;

BankClass Bank;

CardsClass Game_Cards;

GameStatusClass Game_Status;

DiceClass Dice;

OptionsClass Options;

PlayerClass Players[TOTAL_PLAYERS] = {
    PlayerClass(PLAYER_1),
    PlayerClass(PLAYER_2),
    PlayerClass(PLAYER_3),
    PlayerClass(PLAYER_4),
    PlayerClass(PLAYER_5),
    PlayerClass(PLAYER_6),
};

ColorGroupClass Color_Group_Data[TOTAL_COLOR_GROUPS] = {
    ColorGroupClass(COLOR_GROUP_DARK_PURPLE, 50, 2, 11, PROP_MEDITERRANEAN_AVENUE, PROP_BALTIC_AVENUE, PROP_NONE),
    ColorGroupClass(COLOR_GROUP_LIGHT_BLUE, 50, 3, 9, PROP_ORIENTAL_AVENUE, PROP_VERMONT_AVENUE, PROP_CONNECTICUT_AVENUE),
    ColorGroupClass(COLOR_GROUP_PURPLE, 100, 3, 5, PROP_ST_CHARLES_PLACE, PROP_STATES_AVENUE, PROP_VIRGINIA_AVENUE),
    ColorGroupClass(COLOR_GROUP_ORANGE, 100, 3, 21, PROP_ST_JAMES_PLACE, PROP_TENNESSEE_AVENUE, PROP_NEW_YORK_AVENUE),
    ColorGroupClass(COLOR_GROUP_RED, 150, 3, 10, PROP_KENTUCKY_AVENUE, PROP_INDIANA_AVENUE, PROP_ILLINOIS_AVENUE),
    ColorGroupClass(COLOR_GROUP_YELLOW, 150, 3, 251, PROP_ATLANTIC_AVENUE, PROP_VENTNOR_AVENUE, PROP_MARVIN_GARDENS),
    ColorGroupClass(COLOR_GROUP_GREEN, 200, 3, 8, PROP_PACIFIC_AVENUE, PROP_NORTH_CAROLINA_AVENUE, PROP_PENNSYLVANIA_AVENUE),
    ColorGroupClass(COLOR_GROUP_BLUE, 200, 2, 4, PROP_PARK_PLACE, PROP_BOARDWALK, PROP_NONE),
};

PropertyClass Property_Data[TOTAL_PROPERTIES] = {
    PropertyClass(LOC_MEDITERRANEAN_AVENUE, PROP_MEDITERRANEAN_AVENUE, COLOR_GROUP_DARK_PURPLE, TITLE_DEED_TEXT_WHITE, 60, 2,
        10, 30, 90, 160, 250, 30, 50),
    PropertyClass(LOC_BALTIC_AVENUE, PROP_BALTIC_AVENUE, COLOR_GROUP_DARK_PURPLE, TITLE_DEED_TEXT_WHITE, 60, 4, 20, 60, 180,
        320, 450, 30, 50),
    PropertyClass(LOC_ORIENTAL_AVENUE, PROP_ORIENTAL_AVENUE, COLOR_GROUP_LIGHT_BLUE, TITLE_DEED_TEXT_BLACK, 100, 6, 30, 90,
        270, 400, 550, 50, 50),
    PropertyClass(LOC_VERMONT_AVENUE, PROP_VERMONT_AVENUE, COLOR_GROUP_LIGHT_BLUE, TITLE_DEED_TEXT_BLACK, 100, 6, 30, 90,
        270, 400, 550, 50, 50),
    PropertyClass(LOC_CONNECTICUT_AVENUE, PROP_CONNECTICUT_AVENUE, COLOR_GROUP_LIGHT_BLUE, TITLE_DEED_TEXT_BLACK, 120, 8, 40,
        100, 300, 450, 600, 60, 50),
    PropertyClass(LOC_ST_CHARLES_PLACE, PROP_ST_CHARLES_PLACE, COLOR_GROUP_PURPLE, TITLE_DEED_TEXT_WHITE, 140, 10, 50, 150,
        450, 625, 750, 70, 100),
    PropertyClass(LOC_STATES_AVENUE, PROP_STATES_AVENUE, COLOR_GROUP_PURPLE, TITLE_DEED_TEXT_WHITE, 140, 10, 50, 150, 450,
        625, 750, 70, 100),
    PropertyClass(LOC_VIRGINIA_AVENUE, PROP_VIRGINIA_AVENUE, COLOR_GROUP_PURPLE, TITLE_DEED_TEXT_WHITE, 160, 12, 60, 180,
        500, 700, 900, 80, 100),
    PropertyClass(LOC_ST_JAMES_PLACE, PROP_ST_JAMES_PLACE, COLOR_GROUP_ORANGE, TITLE_DEED_TEXT_BLACK, 180, 14, 70, 200, 550,
        750, 950, 90, 100),
    PropertyClass(LOC_TENNESSEE_AVENUE, PROP_TENNESSEE_AVENUE, COLOR_GROUP_ORANGE, TITLE_DEED_TEXT_BLACK, 180, 14, 70, 200,
        550, 750, 950, 90, 100),
    PropertyClass(LOC_NEW_YORK_AVENUE, PROP_NEW_YORK_AVENUE, COLOR_GROUP_ORANGE, TITLE_DEED_TEXT_BLACK, 200, 16, 80, 220,
        600, 800, 1000, 100, 100),
    PropertyClass(LOC_KENTUCKY_AVENUE, PROP_KENTUCKY_AVENUE, COLOR_GROUP_RED, TITLE_DEED_TEXT_WHITE, 220, 18, 90, 250, 700,
        875, 1050, 110, 150),
    PropertyClass(LOC_INDIANA_AVENUE, PROP_INDIANA_AVENUE, COLOR_GROUP_RED, TITLE_DEED_TEXT_WHITE, 220, 18, 90, 250, 700,
        875, 1050, 110, 150),
    PropertyClass(LOC_ILLINOIS_AVENUE, PROP_ILLINOIS_AVENUE, COLOR_GROUP_RED, TITLE_DEED_TEXT_WHITE, 240, 20, 100, 300, 750,
        925, 1100, 120, 150),
    PropertyClass(LOC_ATLANTIC_AVENUE, PROP_ATLANTIC_AVENUE, COLOR_GROUP_YELLOW, TITLE_DEED_TEXT_BLACK, 260, 22, 110, 330,
        800, 975, 1150, 130, 150),
    PropertyClass(LOC_VENTNOR_AVENUE, PROP_VENTNOR_AVENUE, COLOR_GROUP_YELLOW, TITLE_DEED_TEXT_BLACK, 260, 22, 110, 330, 800,
        975, 1150, 130, 150),
    PropertyClass(LOC_MARVIN_GARDENS, PROP_MARVIN_GARDENS, COLOR_GROUP_YELLOW, TITLE_DEED_TEXT_BLACK, 280, 24, 120, 360, 850,
        1025, 1200, 140, 150),
    PropertyClass(LOC_PACIFIC_AVENUE, PROP_PACIFIC_AVENUE, COLOR_GROUP_GREEN, TITLE_DEED_TEXT_WHITE, 300, 26, 130, 390, 900,
        1100, 1275, 150, 200),
    PropertyClass(LOC_NORTH_CAROLINA_AVENUE, PROP_NORTH_CAROLINA_AVENUE, COLOR_GROUP_GREEN, TITLE_DEED_TEXT_WHITE, 300, 26,
        130, 390, 900, 1100, 1275, 150, 200),
    PropertyClass(LOC_PENNSYLVANIA_AVENUE, PROP_PENNSYLVANIA_AVENUE, COLOR_GROUP_GREEN, TITLE_DEED_TEXT_WHITE, 320, 28, 150,
        450, 1000, 1200, 1400, 160, 200),
    PropertyClass(LOC_PARK_PLACE, PROP_PARK_PLACE, COLOR_GROUP_BLUE, TITLE_DEED_TEXT_WHITE, 350, 35, 175, 500, 1100, 1300,
        1500, 175, 200),
    PropertyClass(LOC_BOARDWALK, PROP_BOARDWALK, COLOR_GROUP_BLUE, TITLE_DEED_TEXT_WHITE, 400, 50, 200, 600, 1400, 1700,
        2000, 200, 200),
    PropertyClass(LOC_ELECTRIC_COMPANY, PROP_UTIL_ELECTRIC_COMPANY, COLOR_GROUP_UTILITIES, TITLE_DEED_TEXT_BLACK, 150, 0, 0,
        0, 0, 0, 0, 75, 0),
    PropertyClass(
        LOC_WATER_WORKS, PROP_UTIL_WATER_WORKS, COLOR_GROUP_UTILITIES, TITLE_DEED_TEXT_BLACK, 150, 0, 0, 0, 0, 0, 0, 75, 0),
    PropertyClass(LOC_READING_RAILROAD, PROP_RAILROAD_READING, COLOR_GROUP_RAILROADS, TITLE_DEED_TEXT_BLACK, 200, 25, 0, 0,
        0, 0, 0, 100, 0),
    PropertyClass(LOC_PENNSYLVANIA_RAILROAD, PROP_RAILROAD_PENNSYLVANIA, COLOR_GROUP_RAILROADS, TITLE_DEED_TEXT_BLACK, 200,
        25, 0, 0, 0, 0, 0, 100, 0),
    PropertyClass(LOC_B_AND_O_RAILROAD, PROP_RAILROAD_B_AND_O, COLOR_GROUP_RAILROADS, TITLE_DEED_TEXT_BLACK, 200, 25, 0, 0,
        0, 0, 0, 100, 0),
    PropertyClass(LOC_SHORT_LINE_RAILROAD, PROP_RAILROAD_SHORT_LINE, COLOR_GROUP_RAILROADS, TITLE_DEED_TEXT_BLACK, 200, 25,
        0, 0, 0, 0, 0, 100, 0),
};

BoardLocationClass Board_Location_Data[40] = {
    BoardLocationClass(LOC_GO, 0, 0, 0, 0, EXIT_DIR_LEFT, BOARD_SPOT_TYPE_GO),
    BoardLocationClass(LOC_MEDITERRANEAN_AVENUE, 0, 0, 0, 0, EXIT_DIR_LEFT, BOARD_SPOT_TYPE_PROPERTY),
    BoardLocationClass(LOC_COMMUNITY_CHEST_A, 0, 0, 0, 0, EXIT_DIR_LEFT, BOARD_SPOT_TYPE_COMMUNITY_CHEST),
    BoardLocationClass(LOC_BALTIC_AVENUE, 0, 0, 0, 0, EXIT_DIR_LEFT, BOARD_SPOT_TYPE_PROPERTY),
    BoardLocationClass(LOC_INCOME_TAX, 0, 0, 0, 0, EXIT_DIR_LEFT, BOARD_SPOT_TYPE_INCOME_TAX),
    BoardLocationClass(LOC_READING_RAILROAD, 0, 0, 0, 0, EXIT_DIR_LEFT, BOARD_SPOT_TYPE_RAILROAD),
    BoardLocationClass(LOC_ORIENTAL_AVENUE, 0, 0, 0, 0, EXIT_DIR_LEFT, BOARD_SPOT_TYPE_PROPERTY),
    BoardLocationClass(LOC_CHANCE_A, 0, 0, 0, 0, EXIT_DIR_LEFT, BOARD_SPOT_TYPE_CHANCE),
    BoardLocationClass(LOC_VERMONT_AVENUE, 0, 0, 0, 0, EXIT_DIR_LEFT, BOARD_SPOT_TYPE_PROPERTY),
    BoardLocationClass(LOC_CONNECTICUT_AVENUE, 0, 0, 0, 0, EXIT_DIR_LEFT, BOARD_SPOT_TYPE_PROPERTY),

    BoardLocationClass(LOC_JAIL, 0, 0, 0, 0, EXIT_DIR_UP, BOARD_SPOT_TYPE_JAIL),
    BoardLocationClass(LOC_ST_CHARLES_PLACE, 0, 0, 0, 0, EXIT_DIR_UP, BOARD_SPOT_TYPE_PROPERTY),
    BoardLocationClass(LOC_ELECTRIC_COMPANY, 0, 0, 0, 0, EXIT_DIR_UP, BOARD_SPOT_TYPE_UTILITY),
    BoardLocationClass(LOC_STATES_AVENUE, 0, 0, 0, 0, EXIT_DIR_UP, BOARD_SPOT_TYPE_PROPERTY),
    BoardLocationClass(LOC_VIRGINIA_AVENUE, 0, 0, 0, 0, EXIT_DIR_UP, BOARD_SPOT_TYPE_PROPERTY),
    BoardLocationClass(LOC_PENNSYLVANIA_RAILROAD, 0, 0, 0, 0, EXIT_DIR_UP, BOARD_SPOT_TYPE_RAILROAD),
    BoardLocationClass(LOC_ST_JAMES_PLACE, 0, 0, 0, 0, EXIT_DIR_UP, BOARD_SPOT_TYPE_PROPERTY),
    BoardLocationClass(LOC_COMMUNITY_CHEST_B, 0, 0, 0, 0, EXIT_DIR_UP, BOARD_SPOT_TYPE_COMMUNITY_CHEST),
    BoardLocationClass(LOC_TENNESSEE_AVENUE, 0, 0, 0, 0, EXIT_DIR_UP, BOARD_SPOT_TYPE_PROPERTY),
    BoardLocationClass(LOC_NEW_YORK_AVENUE, 0, 0, 0, 0, EXIT_DIR_UP, BOARD_SPOT_TYPE_PROPERTY),

    BoardLocationClass(LOC_FREE_PARKING, 0, 0, 0, 0, EXIT_DIR_RIGHT, BOARD_SPOT_TYPE_FREE_PARKING),
    BoardLocationClass(LOC_KENTUCKY_AVENUE, 0, 0, 0, 0, EXIT_DIR_RIGHT, BOARD_SPOT_TYPE_PROPERTY),
    BoardLocationClass(LOC_CHANCE_B, 0, 0, 0, 0, EXIT_DIR_RIGHT, BOARD_SPOT_TYPE_CHANCE),
    BoardLocationClass(LOC_INDIANA_AVENUE, 0, 0, 0, 0, EXIT_DIR_RIGHT, BOARD_SPOT_TYPE_PROPERTY),
    BoardLocationClass(LOC_ILLINOIS_AVENUE, 0, 0, 0, 0, EXIT_DIR_RIGHT, BOARD_SPOT_TYPE_PROPERTY),
    BoardLocationClass(LOC_B_AND_O_RAILROAD, 0, 0, 0, 0, EXIT_DIR_RIGHT, BOARD_SPOT_TYPE_RAILROAD),
    BoardLocationClass(LOC_ATLANTIC_AVENUE, 0, 0, 0, 0, EXIT_DIR_RIGHT, BOARD_SPOT_TYPE_PROPERTY),
    BoardLocationClass(LOC_VENTNOR_AVENUE, 0, 0, 0, 0, EXIT_DIR_RIGHT, BOARD_SPOT_TYPE_PROPERTY),
    BoardLocationClass(LOC_WATER_WORKS, 0, 0, 0, 0, EXIT_DIR_RIGHT, BOARD_SPOT_TYPE_UTILITY),
    BoardLocationClass(LOC_MARVIN_GARDENS, 0, 0, 0, 0, EXIT_DIR_RIGHT, BOARD_SPOT_TYPE_PROPERTY),

    BoardLocationClass(LOC_GO_TO_JAIL, 0, 0, 0, 0, EXIT_DIR_DOWN, BOARD_SPOT_TYPE_GO_TO_JAIL),
    BoardLocationClass(LOC_PACIFIC_AVENUE, 0, 0, 0, 0, EXIT_DIR_DOWN, BOARD_SPOT_TYPE_PROPERTY),
    BoardLocationClass(LOC_NORTH_CAROLINA_AVENUE, 0, 0, 0, 0, EXIT_DIR_DOWN, BOARD_SPOT_TYPE_PROPERTY),
    BoardLocationClass(LOC_COMMUNITY_CHEST_C, 0, 0, 0, 0, EXIT_DIR_DOWN, BOARD_SPOT_TYPE_COMMUNITY_CHEST),
    BoardLocationClass(LOC_PENNSYLVANIA_AVENUE, 0, 0, 0, 0, EXIT_DIR_DOWN, BOARD_SPOT_TYPE_PROPERTY),
    BoardLocationClass(LOC_SHORT_LINE_RAILROAD, 0, 0, 0, 0, EXIT_DIR_DOWN, BOARD_SPOT_TYPE_RAILROAD),
    BoardLocationClass(LOC_CHANCE_C, 0, 0, 0, 0, EXIT_DIR_DOWN, BOARD_SPOT_TYPE_CHANCE),
    BoardLocationClass(LOC_PARK_PLACE, 0, 0, 0, 0, EXIT_DIR_DOWN, BOARD_SPOT_TYPE_PROPERTY),
    BoardLocationClass(LOC_LUXURY_TAX, 0, 0, 0, 0, EXIT_DIR_DOWN, BOARD_SPOT_TYPE_LUXURY_TAX),
    BoardLocationClass(LOC_BOARDWALK, 0, 0, 0, 0, EXIT_DIR_DOWN, BOARD_SPOT_TYPE_PROPERTY),
};
#endif